server:
  port: 8082

spring:
  application:
    name: jinjiuDRTM-map
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jinjiu_drtm?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root123

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.jinjiu.drtm.map.domain
  configuration:
    map-underscore-to-camel-case: true

app:
  road-network:
    storage-path: src/main/resources/static/road-network
